# Generated by Django 3.1.1 on 2021-05-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
