# Generated by Django 3.1.1 on 2021-05-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210524_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='image',
            field=models.ImageField(default='14092.jpg', upload_to='profileImages'),
        ),
    ]
